version: '3.8'

services:
  db:
    restart: unless-stopped
    image: mariadb:11.5.2-noble
    container_name: centribal-mariadb-orders
    environment:
      - MARIADB_DATABASE=centribal_orders_db
      - MARIADB_USER=centribal
      - MARIADB_PASSWORD=${MYSQL_CENTRIBAL_PASSWORD:-MYSQL_CENTRIBAL_PASSWORD}
      - MARIADB_RANDOM_ROOT_PASSWORD=1
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql:Z
    healthcheck:
     # Let mariaDB settle before django attempts to connect
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3

  app:
    build:
      context: .
      dockerfile: containers/Dockerfile
    container_name: centribal-django-orders
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-DJANGO_SECRET_KEY}
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=centribal_orders_db
      - DB_USER=centribal
      - DB_PASSWORD=${MYSQL_CENTRIBAL_PASSWORD:-MYSQL_CENTRIBAL_PASSWORD}
    volumes:
      - ./orders:/centribal
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
