# Generated by Django 5.1.1 on 2024-09-11 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reference', models.SlugField()),
                ('name', models.SlugField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='inventory.article')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('new_state', models.PositiveIntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.article')),
            ],
        ),
        migrations.CreateModel(
            name='PricedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=28)),
                ('set_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.article')),
            ],
        ),
    ]
