# Generated by Django 5.1.1 on 2024-09-11 14:42

import django.db.models.deletion
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_category_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=inventory.models.set_default_category, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory.category'),
        ),
    ]
