# Generated by Django 5.1.1 on 2024-09-11 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_taxes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullArticle',
            fields=[
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='inventory.article')),
                ('price', models.DecimalField(decimal_places=2, max_digits=28)),
                ('set_at', models.DateTimeField()),
                ('quantity', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField()),
                ('reference', models.SlugField()),
                ('name', models.SlugField()),
                ('description', models.TextField()),
                ('tax', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
            options={
                'db_table': 'taxed_article',
                'managed': False,
            },
        ),
    ]
