# Generated by Django 5.1.1 on 2024-09-15 11:46
import inventory.models
from django.db import migrations


TRIGGERERS = ["update", "insert"]
TRIGGER_NAME_PREFIX = "audit_inventory_articles_"

drop_sql = "\n".join(f"""DROP TRIGGER IF EXISTS `{TRIGGER_NAME_PREFIX}{triggerer}`;""" for triggerer in TRIGGERERS)


create_sql = "\n".join(f"""
CREATE TRIGGER IF NOT EXISTS `TRIGGER_NAME_PREFIX{triggerer}`
AFTER {triggerer.upper()}
    ON `{inventory.models.InventoryArticle._meta.db_table}`
FOR EACH ROW 
    INSERT INTO `{inventory.models.InventoryAudit._meta.db_table}`
        (`event_date`, `new_state`, `article_id`)
    VALUES(
        CURRENT_TIMESTAMP(6), NEW.quantity, NEW.article_id
    );
""" for triggerer in TRIGGERERS)


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_fullarticle"),
    ]

    operations = [
        migrations.RunSQL(
            create_sql,
            reverse_sql=drop_sql,
        ),
    ]
