# Generated by Django 5.1.1 on 2024-09-11 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_fullarticle'),
        ('sales', '0003_prices_and_taxes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedPurchaceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.SlugField()),
                ('created_at', models.DateTimeField()),
                ('article_reference', models.SlugField()),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=28)),
                ('tax_value', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
            options={
                'db_table': 'order_details',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='orderarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.inventoryarticle'),
        ),
        migrations.AlterField(
            model_name='purchaceorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
