# Generated by Django 5.1.1 on 2024-09-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_orderarticle_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='value',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
